# Generated by Django 5.1.5 on 2025-02-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'product_data',
                'managed': True,
            },
        ),
    ]
