# Generated by Django 5.1.5 on 2025-02-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdatas',
            old_name='productDescription',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='productdatas',
            old_name='productName',
            new_name='product_name',
        ),
    ]
