# Generated by Django 5.1.4 on 2025-02-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdatas',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
